### ISSUE TITLE
mktemp: too few X's in template ‘desktop-image-switcher’

### ISSUE THREAD

**Issue by erikw** [GabrielDougherty/desktop-image-switcher#1]
When running the script I get the following output

```
mktemp: too few X's in template ‘desktop-image-switcher’
```

**Comment by GabrielDougherty** [comment]
Hi Erik, thanks for your contribution. I agree with your analysis, and will merge your fix. But I can't reproduce the mktemp error you are getting. Out of curiosity, can you please post the output of `which mktemp`? Mine is just at `/usr/bin/mktemp`.

**Comment by erikw** [comment]
@GabrielDougherty oh you're right, I did not think of it

```bash
$ which mktemp
/usr/local/opt/coreutils/libexec/gnubin/mktemp
```

So I'm using GNU coreutils. Forgot about that! But I think with the updated pattern, it should work on default macOS mktemp and the coreutils version :)
